<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <Version>1.2.0</Version>
    <Authors>HKW</Authors>
    <Company>HKW</Company>
    <PackageDescription>A dedicated WPF library providing Collections, TypeExtension, MVVMDialogs, and other features.</PackageDescription>
    <PackageTags>MVVM;WPF;Converter;Dialog;Extennsion</PackageTags>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0-windows</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <ImplicitUsings>enable</ImplicitUsings>
    <GenerateDocumentationFile>True</GenerateDocumentationFile>
    <GeneratePackageOnBuild>True</GeneratePackageOnBuild>
    <PackageLicenseExpression>MIT</PackageLicenseExpression>
    <SymbolPackageFormat>snupkg</SymbolPackageFormat>
    <PackageReadmeFile>README.md</PackageReadmeFile>
    <EmitCompilerGeneratedFiles>true</EmitCompilerGeneratedFiles>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>

  <PropertyGroup>
    <ContinuousIntegrationBuild>true</ContinuousIntegrationBuild>
    <Deterministic>true</Deterministic>
    <PathMap Condition="'$(SolutionDir)' != ''">$(SolutionDir)=/_/</PathMap>
    <PathMap Condition="'$(SolutionDir)' == ''"
      >$(MSBuildProjectDirectory)=/_/$(AssemblyName)/</PathMap
    >
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Debug|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(Platform)'=='Release|AnyCPU'">
    <DebugType>embedded</DebugType>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="HKW.Utils" Version="1.4.0" />
    <PackageReference Include="HKW.CommonValueConverters" Version="0.2.0" />
  </ItemGroup>
  <ItemGroup>
    <PackageReference Include="HanumanInstitute.MvvmDialogs" Version="2.4.0" />
    <PackageReference Include="HanumanInstitute.MvvmDialogs.Wpf" Version="2.4.0" />
    <PackageReference Include="Microsoft.Extensions.DependencyInjection" Version="10.0.12" />
    <PackageReference Include="Microsoft.Windows.CsWin32" Version="0.3.333">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.Xaml.Behaviors.Wpf" Version="1.1.158" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\README.md">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

  <!--<ItemGroup>
    <Reference Include="HKW.CommonValueConverters">
      <HintPath>..\..\HKW.CommonValueConverters\HKW.CommonValueConverters\bin\Debug\net10.0\HKW.CommonValueConverters.dll</HintPath>
    </Reference>
    <Reference Include="HKW.Utils">
      <HintPath>..\..\HKW.Utils\HKW.Utils\bin\Debug\net10.0\HKW.Utils.dll</HintPath>
    </Reference>
  </ItemGroup>-->
</Project>
